#!/usr/bin/env bash
# Displays subdomain, record type and IP address

print_record ()
{
	printf "The subdomain %s is a " "$2"
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $4 }'
	printf " record and points to "
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $5 }'
	echo ""
}

if [ -z "$2" ]; then
	for subd in "www" "lb-01" "web-01" "web-02"
	do
		print_record "$1" "$subd"
	done
else
	print_record "$1" "$2"
fi
