#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection is configured as a "301 Moved Permanently"

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html
cat > /etc/nginx/sites-available/default <<EOF
server {
	listen 80;
	listen [::]:80 default_server;
	root   /var/www/html;
	index  index.html index.htm;
	location / {
        try_files \$uri \$uri/ =404;
	add_header X-Served-By \$HOSTNAME;
    }
}
EOF

service nginx restart
