#!/usr/bin/env bash
# automates server fix to enable it listen to port 80

sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
