#!/usr/bin/env bash
# tells a story will the field in /etc/passwd file

while IFS=: read -r username passw uid gid more home cmd; do
	echo "The user $username is part of the $gid gang, lives in $home and rides $cmd. $uid's place is protected by the passcode $passw, more info about the user here: $more"
done < /etc/passwd
