#!/usr/bin/env bash
# loops from 1 to 10 displaying bad luck on the 4th iteration good luck
#+ on the 8th iteration and Best School for the rest

i=1
while [ $i -lt 11 ]; do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
