#!/usr/bin/env bash
# displays numbers from 1 to 20 and back luck from china on the 4th
#+ iteration bad luck from japan on the 9th iteration and bad luck
#+ from italy on the 17th iteration

i=1;
while [ $i -lt 21 ]; do
	echo "$i"
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((i++))
done
