#!/usr/bin/env bash
# displays the time for 12 hours 59 minutes

hr=0
min=0
while [ $hr -lt 13 ]; do
	if [ $min -eq 0 ]; then
		echo "Hour: $hr"
	else
		echo "$min"
	fi
	((min++))
	if [ $min -eq 60 ]; then
		((hr++))
		min=0
	fi
done
